name: "Run Tests"
on:
  push:
    branches: ["*"]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Go tests"
        run: make go_test
      - name: "Java tests"
        run: make java_test
      - name: "Python tests"
        run: make python_test
