name: "Run Tests"
on:
  push:
    branches: ["*"]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.24.0"
      - name: "Go tests"
        run: |
          cd go
          make go_test
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "23"
      - name: "Java tests"
        run: |
          cd java
          make java_test
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: "Python tests"
        run: |
          cd python
          make python_test
